joint_names:
  - shoulder_yaw_joint_left
  - shoulder_pitch_joint_left
  - shoulder_roll_joint_left
  - elbow_pitch_joint_left
  - elbow_roll_joint_left
  - wrist_pitch_joint_left
  - wrist_yaw_joint_left
constraints:
   goal_time: 0.6
   shoulder_yaw_joint_left:
        goal: 0.02
   shoulder_pitch_joint_left:
        goal: 0.02
   shoulder_roll_joint_left:
        goal: 0.02
   elbow_pitch_joint_left:
        goal: 0.02
   elbow_roll_joint_left:
        goal: 0.02
   wrist_pitch_joint_left:
        goal: 0.02
   wrist_yaw_joint_left:
        goal: 0.02
