joint_names:
  - shoulder_yaw_joint_right
  - shoulder_pitch_joint_right
  - shoulder_roll_joint_right
  - elbow_pitch_joint_right
  - elbow_roll_joint_right
  - wrist_pitch_joint_right
  - wrist_yaw_joint_right
constraints:
   goal_time: 0.6
   shoulder_yaw_joint_right:
        goal: 0.02
   shoulder_pitch_joint_right:
        goal: 0.02
   shoulder_roll_joint_right:
        goal: 0.02
   elbow_pitch_joint_right:
        goal: 0.02
   elbow_roll_joint_right:
        goal: 0.02
   wrist_pitch_joint_right:
        goal: 0.02
   wrist_yaw_joint_right:
        goal: 0.02
