joint_names:
  - shoulder_yaw_joint_right
  - shoulder_pitch_joint_right
  - shoulder_roll_joint_right
  - elbow_pitch_joint_right
  - elbow_roll_joint_right
  - wrist_pitch_joint_right
  - wrist_yaw_joint_right
constraints:
   goal_time: 20.0
   shoulder_yaw_joint_right:
        intermediate_goal: 0.02
        trajectory: 10.0
        final_goal: 0.01
   shoulder_pitch_joint_right:
        intermediate_goal: 0.02
        trajectory: 10.0
        final_goal: 0.01
   shoulder_roll_joint_right:
        intermediate_goal: 0.02
        trajectory: 10.0
        final_goal: 0.01
   elbow_pitch_joint_right:
        intermediate_goal: 0.02
        trajectory: 10.0
        final_goal: 0.01
   elbow_roll_joint_right:
        intermediate_goal: 0.02
        trajectory: 10.0
        final_goal: 0.01
   wrist_pitch_joint_right:
        intermediate_goal: 0.02
        trajectory: 10.0
        final_goal: 0.01
   wrist_yaw_joint_right:
        intermediate_goal: 0.02
        trajectory: 10.0
        final_goal: 0.01
