joint_limits:
  torso_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  shoulder_yaw_joint_left:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  shoulder_pitch_joint_left:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  shoulder_roll_joint_left:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  elbow_pitch_joint_left:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  elbow_roll_joint_left:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  wrist_pitch_joint_left:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  wrist_yaw_joint_left:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  shoulder_yaw_joint_right:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  shoulder_pitch_joint_right:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  shoulder_roll_joint_right:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  elbow_pitch_joint_right:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  elbow_roll_joint_right:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  wrist_pitch_joint_right:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  wrist_yaw_joint_right:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false