joint_names:
  - shoulder_yaw_joint_left
  - shoulder_pitch_joint_left
  - shoulder_roll_joint_left
  - elbow_pitch_joint_left
  - elbow_roll_joint_left
  - wrist_pitch_joint_left
  - wrist_yaw_joint_left
constraints:
   goal_time: 10.0
   shoulder_yaw_joint_left:
        intermediate_goal: 0.02
        trajectory: 10.0
        final_goal: 0.01
   shoulder_pitch_joint_left:
        intermediate_goal: 0.02
        trajectory: 10.0
        final_goal: 0.01
   shoulder_roll_joint_right:
        intermediate_goal: 0.02
        trajectory: 10.0
        final_goal: 0.01
   elbow_pitch_joint_right:
        intermediate_goal: 0.02
        trajectory: 10.0
        final_goal: 0.01
   elbow_roll_joint_right:
        intermediate_goal: 0.02
        trajectory: 10.0
        final_goal: 0.01
   wrist_pitch_joint_right:
        intermediate_goal: 0.02
        trajectory: 10.0
        final_goal: 0.01
   wrist_yaw_joint_right:
        intermediate_goal: 0.02
        trajectory: 10.0
        final_goal: 0.01