joint_names:
  - shoulder_yaw_joint_left
  - shoulder_pitch_joint_left
  - shoulder_roll_joint_left
  - elbow_pitch_joint_left
  - elbow_roll_joint_left
  - wrist_pitch_joint_left
  - wrist_yaw_joint_left
constraints:
   goal_time: 10.0
   shoulder_yaw_joint_left:
        intermediate_goal: 0.08
        trajectory: 0.1
        final_goal: 0.06
   shoulder_pitch_joint_left:
        intermediate_goal: 0.08
        trajectory: 0.1
        final_goal: 0.06
   shoulder_roll_joint_left:
        intermediate_goal: 0.08
        trajectory: 0.1
        final_goal: 0.06
   elbow_pitch_joint_left:
        intermediate_goal: 0.08
        trajectory: 0.1
        final_goal: 0.06
   elbow_roll_joint_left:
        intermediate_goal: 0.08
        trajectory: 0.1
        final_goal: 0.06
   wrist_pitch_joint_left:
        intermediate_goal: 0.08
        trajectory: 0.1
        final_goal: 0.06
   wrist_yaw_joint_left:
        intermediate_goal: 0.08
        trajectory: 0.1
        final_goal: 0.06
