joint_names:
  - torso_joint
  - shoulder_yaw_joint_left
  - shoulder_pitch_joint_left
  - shoulder_roll_joint_left
  - elbow_pitch_joint_left
  - elbow_roll_joint_left
  - wrist_pitch_joint_left
  - wrist_yaw_joint_left
constraints:
   goal_time: 20.0
   torso_joint:
        intermediate_goal: 0.02
        trajectory: 0.4
        final_goal: 0.01
        max_vel: 0.2
        max_acc: 0.2
   shoulder_yaw_joint_left:
        intermediate_goal: 0.02
        trajectory: 10.0
        final_goal: 0.02
        min_pos: -3.142
        max_pos: 3.142
        max_vel: 0.4
        max_acc: 0.2
   shoulder_pitch_joint_left:
        intermediate_goal: 0.02
        trajectory: 10.0
        final_goal: 0.02
        min_pos: -3.143
        max_pos: 3.143
        max_vel: 0.4
        max_acc: 0.2
   shoulder_roll_joint_left:
        intermediate_goal: 0.02
        trajectory: 10.0
        final_goal: 0.02
        min_pos: -3.144
        max_pos: 3.144
        max_vel: 0.6
        max_acc: 0.3
   elbow_pitch_joint_left:
        intermediate_goal: 0.02
        trajectory: 10.0
        final_goal: 0.02
        min_pos: -3.145
        max_pos: 3.145
        max_vel: 0.8
        max_acc: 0.5
   elbow_roll_joint_left:
        intermediate_goal: 0.02
        trajectory: 10.0
        final_goal: 0.02
        min_pos: -3.146
        max_pos: 3.146
        max_vel: 0.8
        max_acc: 0.5
   wrist_pitch_joint_left:
        intermediate_goal: 0.02
        trajectory: 10.0
        final_goal: 0.02
        min_pos: -3.147
        max_pos: 3.147
        max_vel: 1.0
        max_acc: 0.5
   wrist_yaw_joint_left:
        intermediate_goal: 0.02
        trajectory: 10.0
        final_goal: 0.02
        min_pos: -3.148
        max_pos: 3.148
        max_vel: 1.0
        max_acc: 0.5
