joint_names:
  - torso_joint
  - shoulder_yaw_joint_left
  - shoulder_pitch_joint_left
  - shoulder_roll_joint_left
  - elbow_pitch_joint_left
  - elbow_roll_joint_left
  - wrist_pitch_joint_left
  - wrist_yaw_joint_left
constraints:
   goal_time: 20.0
   torso_joint:
        intermediate_goal: 0.02
        trajectory: 0.4
        final_goal: 0.01
        max_vel: 1.0
   shoulder_yaw_joint_left:
        intermediate_goal: 0.02
        trajectory: 10.0
        final_goal: 0.02
        max_vel: 1.0
   shoulder_pitch_joint_left:
        intermediate_goal: 0.02
        trajectory: 10.0
        final_goal: 0.02
        max_vel: 1.0
   shoulder_roll_joint_left:
        intermediate_goal: 0.02
        trajectory: 10.0
        final_goal: 0.02
        max_vel: 1.0
   elbow_pitch_joint_left:
        intermediate_goal: 0.02
        trajectory: 10.0
        final_goal: 0.02
        max_vel: 1.0
   elbow_roll_joint_left:
        intermediate_goal: 0.02
        trajectory: 10.0
        final_goal: 0.02
        max_vel: 1.0
   wrist_pitch_joint_left:
        intermediate_goal: 0.02
        trajectory: 10.0
        final_goal: 0.02
        max_vel: 1.0
   wrist_yaw_joint_left:
        intermediate_goal: 0.02
        trajectory: 10.0
        final_goal: 0.02
        max_vel: 1.0
