min_sensor_dist: .05
self_see_default_padding: .01
self_see_default_scale: 1.0
self_see_links:
  - name: base_link
    padding: .04
  - name: torso
    padding: .04  
  - name: torso_slider
    padding: .04  
