self_see_links:
  - name: upper_arm_left
    padding: .04
  - name: shoulder_block_left
    padding: .01
  - name: shoulder_sphere_left
    padding: .01
  - name: fore_arm_left
    padding: .04
  - name: elbow_block_left
    padding: .01
  - name: wrist1_block_left
    padding: .01
  - name: hand_left
    padding: .04
  - name: finger1_left
    padding: .04
  - name: finger2_left
    padding: .04
  - name: grippoint_left
    padding: .04
  - name: upper_arm_right
    padding: .04
  - name: shoulder_block_right
    padding: .01
  - name: shoulder_sphere_right
    padding: .01
  - name: fore_arm_right
    padding: .04
  - name: elbow_block_right
    padding: .01
  - name: wrist1_block_right
    padding: .01
  - name: hand_right
    padding: .04
  - name: finger1_right
    padding: .04
  - name: finger2_right
    padding: .04
  - name: grippoint_right
    padding: .04
  - name: torso
    padding: .01
  - name: base
    padding: .01
  - name: neck
    padding: .01
  - name: head
    padding: .01
  - name: top_laser
    padding: .01
  - name: base_laser
    padding: .01    

               
