## This file should be loaded under <robot description>_planning

## the definition of each group
groups:

  - name: robot_body
    joints:
      spindle_joint
      base_link_joint
    links:
      base_link
      torso
      base

  - name: left_arm
    joints:
      shoulder_yaw_joint_left
      shoulder_pitch_joint_left
      shoulder_roll_joint_left
      elbow_pitch_joint_left
      elbow_roll_joint_left
      wrist_pitch_joint_left
      wrist_yaw_joint_left
    links:
      shoulder_block_left
      shoulder_sphere_left
      upper_arm_left
      elbow_block_left
      fore_arm_left
      wrist1_block_left
      hand_left
      finger1_left
      finger2_left

  - name: right_arm
    joints:
      shoulder_yaw_joint_right
      shoulder_pitch_joint_right
      shoulder_roll_joint_right
      elbow_pitch_joint_right
      elbow_roll_joint_right
      wrist_pitch_joint_right
      wrist_yaw_joint_right
    links:
      shoulder_block_right
      shoulder_sphere_right
      upper_arm_right
      elbow_block_right
      fore_arm_right
      wrist1_block_right
      hand_right
      finger1_right
      finger2_right
      
  - name: arms
    joints: 
      shoulder_yaw_joint_left
      shoulder_pitch_joint_left
      shoulder_roll_joint_left
      elbow_pitch_joint_left
      elbow_roll_joint_left
      wrist_pitch_joint_left
      wrist_yaw_joint_left
      shoulder_yaw_joint_right
      shoulder_pitch_joint_right
      shoulder_roll_joint_right
      elbow_pitch_joint_right
      elbow_roll_joint_right
      wrist_pitch_joint_right
      wrist_yaw_joint_right
    links:
      shoulder_block_left
      shoulder_sphere_left
      upper_arm_left
      elbow_block_left
      fore_arm_left
      wrist1_block_left
      hand_left
      finger1_left
      finger2_left
      shoulder_block_right
      shoulder_sphere_right
      upper_arm_right
      elbow_block_right
      fore_arm_right
      wrist1_block_right
      hand_right
      finger1_right
      finger2_right
    
    planner_configs:
      RRTkConfig2 SBLkConfig2 

  - name: l_end_effector
    links: 
      hand_left
      finger1_left
      finger2_left
      grippoint_left


  - name: r_end_effector
    links: 
      hand_right
      finger1_right
      finger2_right
      grippoint_right

