default_robot_padding: 0.01
link_padding:
  - link: robot_body
    padding: 0.0
  - link: left_arm
    padding: .01
  - link: right_arm 
    padding: .01
  - link: r_end_effector
    padding: .005
  - link: l_end_effector
    padding: .005
  - link: finger1_left
    padding: .001
  - link: finger2_left
    padding: .001
  - link: finger1_right
    padding: .001
  - link: finger2_right
    padding: .001
  - link: attached
    padding: .001
